notifications:
  email: false

# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: GBu06NxHLh9GUwPhjrDkQVu31Ia8sGaQUVzFnCqtbeFLZnR8ec/B5TnTrjeGLQhrz6GFEaxRkxn2RkOBXRcAWFJoVBqUEzoQKWxbFbjbEyiZP5N2jU3fkT0VZcD22whWfSOhiMhTtshxwic7sfbHoISqfQCcj0IYVl14wmR6AdlvoxQYfdJ3wj5m2Gazcb1Pb0up7bydLz48ln2ePDCK5WN7woNxQ788vE02/vgIjnsnDyPcGPR9iuFroCmsgOpcMxNFQhOftqd/5xVxiZXSi4z0rBUqMd3z95niD4I2TcswqVN56oiirW/90CUN0ImMfzAt0yt6VXDEqoe+axqNjW6ODh8Fd3V/3h+p3tmhu+VxIQaSmnnbwEj9aawHPnj52ohmXr8YLJVXUfp9ngDK8RXTT3ey8FFC5myjuO4i45+hxHTa05xKFJIZ+cyOTdeUpRkbGWuVACoDbhFRO9gN7vi5770awJQ7b6ds/MvAf721EAkmlmN1IsUFH/6qrYcwgFaFq/4vqwFJMDU55JdsJxWJFfuRtNUirjQGpIf4yNbQhGNjm7eSJ9WnhQOP8eQ+HeOtiKrELvLCsfKird9iGbUyyBjnZ1sGiwear1ojHGjfsJc9r9p83n+ANuBHMVBLlLacbG6+pfJ043XT3s73HSebguDFv5ND/b5Dp8Ejywo=

# Language options
language: node_js
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
node_js:
  - "0"
  - 4
  - 5
before_script:
  - npm prune
script:
  - npm run cover
  - npm run lint

# Npm publish options
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: oKBlJYTRZTK4Wpf2srEXiYYQDDZg5OJuOnzNZ0ntObUMkuJV5KMIUPKJLF2XDMRj+BR69/i7rukk8xSK67X82cAQ2cIvEiEfjb4ozuTmjWYJLItQ4c2RYER+4XZ9REu5FUDB9xYOSS9Gy7EPLBtVmCwunnLIH8erN2MlaEQrP2RkG8KgW+014i7kO/gyuGLk29VxZkTRFoxLpx5mzfElnIGxCdos/5vivWPiWYkXegg5b2MfRJ46Zr380lg0L9Xl1CnQq8bddHW3PdF1y8RVMClu6vFuligQAwDckm3sXnOMLYntkOgUVRvDhd2Gh1hVF6wad30REbduvefpWRV0SpcTDYncUYmmQcF7OEosoq0LluTMKq63v3XQ9ITepfmVXzhXWn2LkzeTKT5XLUitG5S3eYs7sexWF5O2xoZOWwhp5L9UN+dKWT2sUMQL3DSRUQ84o4K+pTA9wlonYPRU2FqvIpA03sQKVdaKrfTSGZan9eTahJXHnRUsagVHP4esmKLFbkIk1aph2bP6v/qy/aWC0P86IWskGuCBqqY5P4lPopJzp1mSTaQdFw/f9Z3wutRT7BzWw8mUntDna09rFysYVQsWzEsv6/nl13BXewRIJN3z4DvGgSXNvAhPFYcvFabm2Rb6HqiAkEY//E69SWXEyJ0JyC4ekR5x7y6Wlmk=
  on:
    node: 4
