notifications:
  email: false

# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: T/9RfCEvUxdNIxIQcIJAzr2nidQMq+6mMHlbO9JcP/oDFNNtQQFObghAqoTxoZxOwFYLK1LjcLP7lPURDKjp0fhJ9bk2SgX8wMaWkdiab2ax7FY/Jw7mWHJ+jME9ne2tr+revTJ2ca2US6JORb7zaSg+nxL8n0h3oMj26Trm9rYGoGOFfpE1vP1PYxQi3Vhh1oD1LVd9nhu8mKmcHvh5asJxnPy/J0aVtAe+h0BLUhpOA4M8nRB9wKipEbmXCjcL2lq8GthEGFlBH5URtrZjkhTWrMM7Tl0yDCnODyNyyj1ipVGXGpWcT6/NFxYlSNNoJ20G6MXm7TXJpMVWJ6FHnYgmI2MsORHtNIeyyCtoSqx/E5t39bCEIhEJSDf9rgqJZhnX8JLz572Gy26ZMlefkymEn2ONGyOM6aUavet/ytLBDkRU/5g6MZ5TVWX3x4jkk9KDNxMFeaIVhMcTWYDwB0q4p4H8ACFyGjBEhevrm3zPKzFAxsQOTawyLvyjwMM828gfhIWv3fzTDqpmgQPPixphxJI47qUsUWtNaBNIuj/QL5Zf6C0mkvIpiLHs+BzrdN9jp2Ybag4Qzm22UAk7qA3RUTqw04bGAC149a1bMZqjJGv35HfW/vjbBwgqKt2qBYpyfLqCr7f4Q92+IsxWCeUCBJUGoOZsYnk80nMEsFs=

# Language options
language: node_js
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
node_js:
  - 4
before_script:
  - npm prune
script:
  - npm run cover
  - npm run lint

# Npm publish options
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: c7RLH83xcBtjiSa9DaoqD0K5NXK3DuMyyeCshN9G5+Hxf4td+/sImts7nMR6aKTnO5RNhMHmiQK9x8Iy5RsdV+MD2NPYBOdrO8qWi53uTzQthdvsoR92XOYFXNyj3GVmw2whL47+HakBwvgSZDguaegpqRI/q9h54wuoYqtxCKvCQogX8Q7Ja1LBsH8UAniBkDYOSA1ONHPX9gr0h4nNs0mCq991m2kkw/3tKzNNOefUu+a/rvDI5alxDJ0+OIZrGFmYXXHUvh/wvnC2vI3dN2MlpATOJZBg6cGECgx8YbJttkbxsKWUPR9YXm1Iq3QDBEQBfk2DtOV3jM5tsDu3mN9GFePiuILSoa9oUR3C/NYmYQZ9JjY0oy6ECWCAHZZANULfMicj6cFkNNpJpnFRQPa+8gO8Gdy8oXk0sSXQhVyfs8vI54Vq5IPPTEDATDlIBq72cyVcPyOxC7XSXSh+G4EzVL0rBJGmdgCwZO9c1xIs1jk9xQMTQDjr9X8FsOrz5HVyftCVZck7qgjskWypOkOKHNVzayeNakobVA5uz0HFPcOyUpXPX6OXq6v25h1sHio6Wk5Jo7Xz/rgUhE+1Pqkt8lGzmkGCQ7hBO2YFT00AMRoVETAPvQHvRU/b2wQLJjdto3boCSDnpAM1dqoUVN5hSMifzCUXZiCqJWKStSs=
  on:
    node: 4
